### ISSUE TITLE
引用

### ISSUE THREAD

**Issue by Qinghao-Guan** [yuting-wei/CCPD#1]
您好，
请问如果我要引用这个数据集，有什么文章我可以引吗？

谢谢！

**Comment by yuting-wei** [comment]
你好，我们的论文还未正式发表，你可以先引用此github链接。等正式发表后，会更新到readme中。谢谢！

**Comment by Qinghao-Guan** [comment]
> 你好，我们的论文还未正式发表，你可以先引用此github链接。等正式发表后，会更新到readme中。谢谢！

好的，谢谢您！
