### ISSUE TITLE
数据集来源

### ISSUE THREAD

**Issue by tianbulapaomo** [yuting-wei/CCPD#2]
您好，请问该数据集是来源于人工标注还是数据采集或是模型标注呢？

**Comment by yuting-wei** [comment]
你好，该数据集来源于数据采集和人工标注相结合的方式。

**Comment by tianbulapaomo** [comment]
> 你好，该数据集来源于数据采集和人工标注相结合的方式。

感谢，隔壁是用这个数据集做的多标签分类模型吗？

**Comment by yuting-wei** [comment]
poka在该数据集上进行了实验，具体内容可以参考我们的相关论文。
